export const GET_USERS_REQUEST = 'GET_USERS_REQUEST';
export const GET_USERS_SUCCESS = 'GET_USERS_SUCCESS';
export const USER_SELECT = 'USER_SELECT';
export const USER_CLEAR = 'USER_CLEAR';
export const DELETE_USERS_REQUEST = 'DELETE_USERS_REQUEST';
export const DELETE_USER_SUCCESS = 'DELETE_USER_SUCCESS';
